// Installer for the Cursor 1.7+ hook adapter. Spec: ADR 0014 §8.
//
// Idempotent: running twice produces a byte-identical
// `~/.cursor/hooks.json`. Non-Warden hook entries are preserved;
// existing Warden entries for the same event are replaced. Every
// Warden-registered entry sets `failClosed: true` so a crashed
// Warden binary becomes a deny rather than a silent pass.

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, resolve } from 'node:path';

type Streams = {
  readonly stdout: { write(chunk: string): boolean | unknown };
  readonly stderr: { write(chunk: string): boolean | unknown };
};

export type InstallOptions = {
  readonly home?: string;
  readonly hooksJsonPath?: string;
  readonly hookScriptPath?: string;
  // Absolute path to the warden CLI entry the wrapper should exec.
  // Defaults to the running process's argv[1]; tests inject a value.
  readonly wardenBinPath?: string;
  // Force overwriting a competing non-Warden hook entry for the same
  // event. Not exposed on the CLI in M7; reserved for the bug case.
  readonly force?: boolean;
};

export type InstallResult = {
  readonly exitCode: number;
  readonly hooksJsonPath: string;
  readonly hookScriptPath: string;
  readonly changed: boolean;
};

// Events the Warden adapter intercepts (ADR 0014 §5). Edit/Write
// coverage is absent because Cursor exposes no pre-write event.
const WARDEN_EVENTS: ReadonlyArray<string> = ['beforeReadFile', 'beforeShellExecution'];

const WARDEN_HOOK_MARKER = '# warden-managed: cursor hook adapter (ADR 0014)';

function buildWrapperScript(wardenBinPath: string): string {
  return [
    '#!/usr/bin/env bash',
    WARDEN_HOOK_MARKER,
    '# Generated by `warden hooks install cursor`. To uninstall, delete this',
    '# file and remove the matching entries from ~/.cursor/hooks.json.',
    'set -eu',
    `exec bun ${shellQuote(wardenBinPath)} hooks run cursor`,
    '',
  ].join('\n');
}

function shellQuote(s: string): string {
  if (/^[\w@/.+:=-]+$/.test(s)) return s;
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

type CursorHookEntry = {
  command?: string;
  failClosed?: boolean;
  timeout?: number;
  matcher?: string;
  [k: string]: unknown;
};

type CursorHooks = {
  [eventName: string]: CursorHookEntry[] | undefined;
};

type CursorHooksFile = {
  hooks?: CursorHooks;
  [k: string]: unknown;
};

function readHooksFile(path: string): { file: CursorHooksFile; existed: boolean } {
  if (!existsSync(path)) return { file: {}, existed: false };
  const text = readFileSync(path, 'utf8');
  if (text.trim().length === 0) return { file: {}, existed: true };
  const parsed = JSON.parse(text);
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(`hooks.json is not a JSON object: ${path}`);
  }
  return { file: parsed as CursorHooksFile, existed: true };
}

function isWardenEntry(entry: CursorHookEntry): boolean {
  if (typeof entry.command !== 'string') return false;
  return entry.command.includes('cursor-pre-tool-use.sh');
}

export function mergeHooksFile(
  base: CursorHooksFile,
  hookScriptPath: string,
  opts: { force: boolean },
): { file: CursorHooksFile; conflicts: ReadonlyArray<string> } {
  const command = shellQuote(hookScriptPath);
  const wardenEntry: CursorHookEntry = { command, failClosed: true };

  const hooks: CursorHooks = { ...(base.hooks ?? {}) };
  const conflicts: string[] = [];

  for (const event of WARDEN_EVENTS) {
    const existing = Array.isArray(hooks[event]) ? [...(hooks[event] as CursorHookEntry[])] : [];
    const nonWarden: CursorHookEntry[] = [];
    let hadWarden = false;
    for (const h of existing) {
      if (isWardenEntry(h)) {
        hadWarden = true;
        continue;
      }
      nonWarden.push(h);
    }
    if (nonWarden.length > 0 && !opts.force && !hadWarden) {
      conflicts.push(event);
      // Keep the array untouched when conflicting.
      hooks[event] = existing;
      continue;
    }
    hooks[event] = [...nonWarden, wardenEntry];
  }

  if (conflicts.length > 0) {
    return { file: base, conflicts };
  }
  return { file: { ...base, hooks }, conflicts: [] };
}

export function installCursorHook(opts: InstallOptions, streams: Streams): InstallResult {
  const home = opts.home ?? homedir();
  const hooksJsonPath = opts.hooksJsonPath ?? resolve(home, '.cursor', 'hooks.json');
  const hookScriptPath =
    opts.hookScriptPath ?? resolve(home, '.warden', 'hooks', 'cursor-pre-tool-use.sh');
  const wardenBinPath =
    opts.wardenBinPath ??
    (typeof process.argv[1] === 'string' ? resolve(process.argv[1]) : 'warden');

  let base: CursorHooksFile;
  let existed: boolean;
  try {
    const read = readHooksFile(hooksJsonPath);
    base = read.file;
    existed = read.existed;
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    streams.stderr.write(`warden hooks install: ${msg}\n`);
    return { exitCode: 1, hooksJsonPath, hookScriptPath, changed: false };
  }

  const merged = mergeHooksFile(base, hookScriptPath, { force: opts.force === true });
  if (merged.conflicts.length > 0) {
    streams.stderr.write(
      `warden hooks install: non-Warden hook entries are already registered for event(s) "${merged.conflicts.join(', ')}" at ${hooksJsonPath}\n  resolve manually, then re-run install\n`,
    );
    return { exitCode: 1, hooksJsonPath, hookScriptPath, changed: false };
  }

  const serialized = `${JSON.stringify(merged.file, null, 2)}\n`;
  const prevSerialized = existed
    ? (() => {
        try {
          return readFileSync(hooksJsonPath, 'utf8');
        } catch {
          return '';
        }
      })()
    : '';

  const wrapperScript = buildWrapperScript(wardenBinPath);
  const wrapperExisting = existsSync(hookScriptPath) ? readFileSync(hookScriptPath, 'utf8') : '';

  const hooksChanged = serialized !== prevSerialized;
  const wrapperChanged = wrapperScript !== wrapperExisting;

  if (hooksChanged) {
    mkdirSync(dirname(hooksJsonPath), { recursive: true });
    writeFileSync(hooksJsonPath, serialized, { encoding: 'utf8' });
  }
  if (wrapperChanged) {
    mkdirSync(dirname(hookScriptPath), { recursive: true });
    writeFileSync(hookScriptPath, wrapperScript, { encoding: 'utf8' });
  }
  try {
    chmodSync(hookScriptPath, 0o755);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    streams.stderr.write(`warden hooks install: chmod failed for ${hookScriptPath}: ${msg}\n`);
    return {
      exitCode: 1,
      hooksJsonPath,
      hookScriptPath,
      changed: hooksChanged || wrapperChanged,
    };
  }

  return {
    exitCode: 0,
    hooksJsonPath,
    hookScriptPath,
    changed: hooksChanged || wrapperChanged,
  };
}
