// Installer for the Claude Code PreToolUse hook adapter.
// Spec: ADR 0013 §§7-8.
//
// Idempotent: running twice produces a byte-identical
// `~/.claude/settings.json`. Non-Warden hook entries are preserved;
// existing Warden entries for the same matcher are replaced.

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, resolve } from 'node:path';

type Streams = {
  readonly stdout: { write(chunk: string): boolean | unknown };
  readonly stderr: { write(chunk: string): boolean | unknown };
};

export type InstallOptions = {
  readonly home?: string;
  readonly settingsPath?: string;
  readonly hookScriptPath?: string;
  // Absolute path to the warden CLI entry the wrapper should exec.
  // Defaults to the running process's argv[1] (the active warden
  // binary), which lets `warden hooks install claude` always wire the
  // currently-running CLI into the hook. Tests pass an explicit value.
  readonly wardenBinPath?: string;
  // Force overwriting a competing non-Warden hook entry with the same
  // matcher. Not exposed on the CLI in M6; reserved for the bug case.
  readonly force?: boolean;
};

export type InstallResult = {
  readonly exitCode: number;
  readonly settingsPath: string;
  readonly hookScriptPath: string;
  readonly changed: boolean;
};

const MATCHER = 'Read|Edit|Write|Bash|MultiEdit';

const WARDEN_HOOK_MARKER = '# warden-managed: claude pre-tool-use hook (ADR 0013)';

function buildWrapperScript(wardenBinPath: string): string {
  // The wrapper is intentionally minimal. It exec's the Warden binary
  // with the `hooks run claude` subcommand and forwards stdin/stdout/
  // stderr. We use `exec` so signals propagate cleanly and there is
  // no shell process lingering after the decision.
  //
  // The shebang uses /usr/bin/env bash for portability. macOS ships
  // bash 3.2; we deliberately avoid any bash 4-only syntax.
  return [
    '#!/usr/bin/env bash',
    WARDEN_HOOK_MARKER,
    '# Generated by `warden hooks install claude`. To uninstall, delete this',
    '# file and remove the matching entry from ~/.claude/settings.json.',
    'set -eu',
    `exec bun ${shellQuote(wardenBinPath)} hooks run claude`,
    '',
  ].join('\n');
}

function shellQuote(s: string): string {
  if (/^[\w@/.+:=-]+$/.test(s)) return s;
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

type SettingsHookEntry = {
  type?: string;
  command?: string;
  [k: string]: unknown;
};

type SettingsHookMatcher = {
  matcher?: string;
  hooks?: SettingsHookEntry[];
  [k: string]: unknown;
};

type ClaudeSettings = {
  hooks?: {
    PreToolUse?: SettingsHookMatcher[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
};

function readSettings(path: string): { settings: ClaudeSettings; existed: boolean } {
  if (!existsSync(path)) return { settings: {}, existed: false };
  const text = readFileSync(path, 'utf8');
  if (text.trim().length === 0) return { settings: {}, existed: true };
  const parsed = JSON.parse(text);
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(`settings.json is not a JSON object: ${path}`);
  }
  return { settings: parsed as ClaudeSettings, existed: true };
}

function isWardenEntry(entry: SettingsHookEntry): boolean {
  if (typeof entry.command !== 'string') return false;
  return entry.command.includes('warden') && entry.command.includes('hooks');
}

export function mergeSettings(
  base: ClaudeSettings,
  hookScriptPath: string,
  opts: { force: boolean },
): { settings: ClaudeSettings; conflict: SettingsHookMatcher | null } {
  const command = shellQuote(hookScriptPath);
  const wardenEntry: SettingsHookEntry = { type: 'command', command };

  const hooks = { ...(base.hooks ?? {}) };
  const preToolUse: SettingsHookMatcher[] = Array.isArray(hooks.PreToolUse)
    ? [...(hooks.PreToolUse as SettingsHookMatcher[])]
    : [];

  let matcherIdx = -1;
  for (let i = 0; i < preToolUse.length; i++) {
    const m = preToolUse[i];
    if (m !== undefined && m.matcher === MATCHER) {
      matcherIdx = i;
      break;
    }
  }

  if (matcherIdx === -1) {
    preToolUse.push({ matcher: MATCHER, hooks: [wardenEntry] });
  } else {
    const m = preToolUse[matcherIdx] as SettingsHookMatcher;
    const existingHooks = Array.isArray(m.hooks) ? [...m.hooks] : [];
    const nonWarden: SettingsHookEntry[] = [];
    let hadWarden = false;
    for (const h of existingHooks) {
      if (isWardenEntry(h)) {
        hadWarden = true;
        continue;
      }
      nonWarden.push(h);
    }
    if (nonWarden.length > 0 && !opts.force && !hadWarden) {
      return { settings: base, conflict: m };
    }
    preToolUse[matcherIdx] = { ...m, matcher: MATCHER, hooks: [...nonWarden, wardenEntry] };
  }

  hooks.PreToolUse = preToolUse;
  return { settings: { ...base, hooks }, conflict: null };
}

export function installClaudeHook(opts: InstallOptions, streams: Streams): InstallResult {
  const home = opts.home ?? homedir();
  const settingsPath = opts.settingsPath ?? resolve(home, '.claude', 'settings.json');
  const hookScriptPath =
    opts.hookScriptPath ?? resolve(home, '.warden', 'hooks', 'claude-pre-tool-use.sh');
  const wardenBinPath =
    opts.wardenBinPath ??
    (typeof process.argv[1] === 'string' ? resolve(process.argv[1]) : 'warden');

  let base: ClaudeSettings;
  let existed: boolean;
  try {
    const read = readSettings(settingsPath);
    base = read.settings;
    existed = read.existed;
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    streams.stderr.write(`warden hooks install: ${msg}\n`);
    return { exitCode: 1, settingsPath, hookScriptPath, changed: false };
  }

  const merged = mergeSettings(base, hookScriptPath, { force: opts.force === true });
  if (merged.conflict !== null) {
    streams.stderr.write(
      `warden hooks install: a non-Warden PreToolUse hook is already registered for matcher "${MATCHER}" at ${settingsPath}\n  resolve manually, then re-run install\n`,
    );
    return { exitCode: 1, settingsPath, hookScriptPath, changed: false };
  }

  const serialized = `${JSON.stringify(merged.settings, null, 2)}\n`;
  const prevSerialized = existed
    ? (() => {
        try {
          return readFileSync(settingsPath, 'utf8');
        } catch {
          return '';
        }
      })()
    : '';

  const wrapperScript = buildWrapperScript(wardenBinPath);
  const wrapperExisting = existsSync(hookScriptPath) ? readFileSync(hookScriptPath, 'utf8') : '';

  const settingsChanged = serialized !== prevSerialized;
  const wrapperChanged = wrapperScript !== wrapperExisting;

  if (settingsChanged) {
    mkdirSync(dirname(settingsPath), { recursive: true });
    writeFileSync(settingsPath, serialized, { encoding: 'utf8' });
  }
  if (wrapperChanged) {
    mkdirSync(dirname(hookScriptPath), { recursive: true });
    writeFileSync(hookScriptPath, wrapperScript, { encoding: 'utf8' });
  }
  // Always chmod — even on no-op runs we want to guarantee +x in case
  // the file lost the bit between runs.
  try {
    chmodSync(hookScriptPath, 0o755);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    streams.stderr.write(`warden hooks install: chmod failed for ${hookScriptPath}: ${msg}\n`);
    return {
      exitCode: 1,
      settingsPath,
      hookScriptPath,
      changed: settingsChanged || wrapperChanged,
    };
  }

  return {
    exitCode: 0,
    settingsPath,
    hookScriptPath,
    changed: settingsChanged || wrapperChanged,
  };
}
